-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "Brand_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) ,
    alias character varying(100) ,
    "imageId" integer,
    "orderIndex" integer,
    "isPopular" boolean,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    "createDate" timestamp without time zone,
    "updateDate" timestamp without time zone,
    CONSTRAINT "PK_Brand_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Category_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) ,
    alias character varying(100) ,
    "imageId" integer,
    "orderIndex" integer,
    "isPopular" boolean,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    "createDate" timestamp without time zone,
    "updateDate" timestamp without time zone,
    CONSTRAINT "PK_Category_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Image_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) ,
    alias character varying(100) ,
    url text ,
    size integer,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    "createDate" timestamp without time zone,
    "updateDate" timestamp without time zone,
    CONSTRAINT "PK_Image_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "OrderDetail_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "orderId" integer,
    "productId" integer,
    price integer,
    quantity integer,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    CONSTRAINT "PK_OrderDetail_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "OrderStatus_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) ,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    CONSTRAINT "PK_OrderStatus_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "OrderVoucher_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) ,
    "shortDes" character varying(2000) ,
    code character varying(10) ,
    value integer,
    "createDate" timestamp without time zone,
    "updateDate" timestamp without time zone,
    "endDate" timestamp without time zone,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    CONSTRAINT "PK_OrderVoucher_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Order_0256"
(
    id integer NOT NULL DEFAULT nextval('"Order_0256_id_seq"'::regclass),
    "userId" integer,
    "createDate" timestamp(3) without time zone,
    "updateDate" timestamp(3) without time zone,
    "voucherSale" integer,
    "isPublic" boolean DEFAULT true,
    "isTrash" boolean DEFAULT false,
    "statusId" integer,
    CONSTRAINT "PK__Order_02__3213E83F9539BFEF" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "ProductImage_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    alt character varying(100) ,
    "productId" integer,
    "imageId" integer,
    "isDefault" boolean DEFAULT false,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    CONSTRAINT "PK_ProductImage_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "ProductRating_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "productId" integer,
    "userId" integer,
    vote integer,
    "createDate" timestamp without time zone,
    "updateDate" timestamp without time zone,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    "fullDes" text ,
    CONSTRAINT "PK_ProductRating_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "ProductType_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) ,
    alias character varying(100) ,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    CONSTRAINT "PK_ProductType_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Product_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) ,
    alias character varying(100) ,
    price integer,
    "salePrice" integer,
    "currencyUnit" character(1) ,
    "shortDes" character varying(2000) ,
    "categoryId" integer,
    "brandId" integer,
    "typeId" integer,
    "createDate" timestamp without time zone,
    "updateDate" timestamp without time zone,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    "fullDes" text ,
    properties text ,
    CONSTRAINT "PK_Product_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "Slider_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    alt character varying(100) ,
    "imageId" integer,
    "orderIndex" integer,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    CONSTRAINT "PK_Slider_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "UserType_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) ,
    alias character varying(100) ,
    "shortDes" character varying(200) ,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    CONSTRAINT "PK_UserType_0256" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "User_0256"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "firstName" character varying(100) ,
    "lastName" character varying(100) ,
    email character varying(100) ,
    password character varying(100) ,
    "typeId" integer,
    "isPublic" boolean DEFAULT false,
    "isTrash" boolean DEFAULT false,
    "imageId" integer,
    phone character(10) ,
    location text ,
    "createDate" timestamp without time zone,
    "updateDate" timestamp without time zone,
    CONSTRAINT "PK_User_0256" PRIMARY KEY (id)
);

END;