# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Asp_Core_Api_TechStore.NET 
# Name of the workflow.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
        
    - name: Build with dotnet
      run: dotnet publish --configuration Release --output build
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          BASE_BRANCH: main # The branch the action should deploy from.
          BRANCH: main_base # The branch the action should deploy to.
          FOLDER:  build
          SINGLE_COMMIT: true
