# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Asp_Core_Api_TechStore.NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build with dotnet
      run: dotnet build --configuration Release 
  deployment:
    runs-on: ubuntu-latest     
    steps:
    - name: Deploy to Netlify 
      #create Blazor WebAssembly dist output folder in the project directory
      run: dotnet publish -c Release --no-build -o publishoutput # Don't build again, just publish
    - name: Publish generated Blazor webassembly to Netlify
      uses: odanado/deploy-to-netlify-action@test/v0.0.15
      with:
        dist-dir: /Application
        netlify-site-id: ${{ secret.NETLIFT_SITE_ID }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        github-token: ${{ github.token }}

