# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Asp_Core_Api_TechStore.NET 
# Name of the workflow.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main # Checkout the main branch
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3 # Setup .NET Core
      with:
        dotnet-version: 5.0.x # Change to your version of .NET Core
    - name: Build with dotnet
      run: dotnet build --configuration Release 
    - name: Publish Blazor webassembly using dotnet 
      #create Blazor WebAssembly dist output folder in the project directory
      run: dotnet publish -c Release --no-build -o release # Don't build again, just publish
    - name: Publish generated Blazor webassembly to Netlify
      uses: netlify/actions/cli@main #uses Netlify Cli actions
      env: # These are the environment variables added in GitHub Secrets for this repo
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
          args: deploy --dir=release/wwwroot --prod #push this folder to Netlify
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ github.token }}
        BRANCH: main_page
        FOLDER: release
